name: CI

on:
  push:
    branches:
      - "*"
  workflow_call:

jobs:
  ci:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: neslinesli93/qpdf-wasm:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract artifacts
        uses: shrink/actions-docker-extract@v3
        id: extract
        with:
          image: neslinesli93/qpdf-wasm:latest
          path: /opt/qpdf/.

      - name: Copy artifacts
        run: cp -r ${{ steps.extract.outputs.destination }} ./dist

      - name: Tests
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          yarn
          yarn test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ github.ref_type == 'tag' }}
        with:
          name: node-app
          path: ./dist
