name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: neslinesli93/qpdf-wasm:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract artifacts
        uses: shrink/actions-docker-extract@v2
        id: extract
        with:
          image: neslinesli93/qpdf-wasm:latest
          path: /opt/qpdf/.

      - name: Copy artifacts
        run: cp -r ${{ steps.extract.outputs.destination }} ./dist

      - name: Tests
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          yarn
          yarn test

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          name: node-app
          path: ./dist
